// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomfNxeqgDxJPHKhnenc_M0FWzCvcZTxM',
    appId: '1:111896486650:web:c8bbd467bd5c9bf5e85f43',
    messagingSenderId: '111896486650',
    projectId: 'mobileappproject-b72eb',
    authDomain: 'mobileappproject-b72eb.firebaseapp.com',
    storageBucket: 'mobileappproject-b72eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lZ5bNEeLEKKiKJwZYQH4g5PtEFo60rA',
    appId: '1:111896486650:android:f02f0ee13eff5f0be85f43',
    messagingSenderId: '111896486650',
    projectId: 'mobileappproject-b72eb',
    storageBucket: 'mobileappproject-b72eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbjTmvfCxBK_imGslhtPg4a59dGqB23k',
    appId: '1:111896486650:ios:f090db6054308293e85f43',
    messagingSenderId: '111896486650',
    projectId: 'mobileappproject-b72eb',
    storageBucket: 'mobileappproject-b72eb.firebasestorage.app',
    iosBundleId: 'com.example.sellingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbjTmvfCxBK_imGslhtPg4a59dGqB23k',
    appId: '1:111896486650:ios:f090db6054308293e85f43',
    messagingSenderId: '111896486650',
    projectId: 'mobileappproject-b72eb',
    storageBucket: 'mobileappproject-b72eb.firebasestorage.app',
    iosBundleId: 'com.example.sellingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomfNxeqgDxJPHKhnenc_M0FWzCvcZTxM',
    appId: '1:111896486650:web:d485270731f96dd5e85f43',
    messagingSenderId: '111896486650',
    projectId: 'mobileappproject-b72eb',
    authDomain: 'mobileappproject-b72eb.firebaseapp.com',
    storageBucket: 'mobileappproject-b72eb.firebasestorage.app',
  );
}
